### PR TITLE
Create Kreutz.txt

### PR DESCRIPTION
**Pull request by Yeqzids**
synthetic population of Kreutz comets

### CODE REVIEW

**Comment by mkelley** [comment]
Looks good.  Just need to add a column that specifies the elements format (COM) and convert the dates to modified Julian date.  Then use the following for the header line:

`!!OID FORMAT q e i node argperi t_p t_0 H`

Using the correct order for your file.  (OID is object ID, t_0 is epoch).  The reader may be more flexible, but if you make these changes I know that it will work.  The only thing I'm unsure about is if H is required, but dummy values are OK.  Maybe just use 26 for all of them.

**Comment by mkelley** [comment]
Also please place a brief description in the README.

**Comment by Yeqzids** [comment]
All implemented... how is it now?

**Comment by mkelley** [comment]
Great, thanks.

**Pull request merged**
